import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {PGlite} from '@electric-sql/pglite';
test('database migrations, account isolation and optimistic revision',async()=>{
 const db=new PGlite();await db.exec(`create role anon; create role authenticated; create role service_role; create schema auth; create table auth.users(id uuid primary key); create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$; grant usage on schema auth to authenticated; create schema storage; create table storage.buckets(id text primary key,name text,public boolean); create table storage.objects(id uuid,bucket_id text,name text); alter table storage.objects enable row level security; create function storage.foldername(text) returns text[] language sql as $$select string_to_array($1,'/')$$;`);
 for(const file of ['202610020001_smartmeal.sql','202610020002_catalog.sql','202610050001_combo_limit.sql'])await db.exec(await readFile(new URL('../supabase/migrations/'+file,import.meta.url),'utf8'));
 const alice='00000000-0000-0000-0000-000000000001',bob='00000000-0000-0000-0000-000000000002';await db.query('insert into auth.users values($1),($2)',[alice,bob]);
 await db.exec(`set role authenticated; set request.jwt.claim.sub='${alice}';`);
 const a:any=(await db.query('select public.smartmeal_load() as result')).rows[0];assert.equal(a.result.data.persona,'hin');assert.equal(a.result.revision,0);
 const next={...a.result.data,profile:{name:'Test',goal:'test-only',taste:'Thanh đạm'}};
 const saved:any=(await db.query('select public.smartmeal_save($1,0) as result',[JSON.stringify(next)])).rows[0];assert.equal(saved.result.revision,1);
 await assert.rejects(()=>db.query('select public.smartmeal_save($1,0)',[JSON.stringify(next)]),/thiết bị khác/);
 await assert.rejects(()=>db.query('update public.smartmeal_accounts set revision=90'),/permission denied/);
 await db.exec(`set request.jwt.claim.sub='${bob}';`);await db.query('select public.smartmeal_load()');
 const rows:any=await db.query('select user_id from public.smartmeal_accounts');assert.deepEqual(rows.rows.map((r:any)=>r.user_id),[bob]);
 const wrong={...next,records:[{id:'r',date:'2026-10-03',time:'09:00',duration:0}]};await assert.rejects(()=>db.query('select public.smartmeal_save($1,0)',[JSON.stringify(wrong)]),/lớn hơn 0/);
 const forged={...next,occasions:[{id:'o',operationId:'o',date:'2026-10-03',slot:'Bữa sáng',dishes:[{id:'d',recipeId:alice,recommendationId:alice,generatedAt:'2026-10-03T01:00:00Z'}]}]};await assert.rejects(()=>db.query('select public.smartmeal_save($1,0)',[JSON.stringify(forged)]),/Nguồn món/);
 const streakHack={...next,firstUse:'2000-01-01',streakDays:['2000-01-01']};await db.query('select public.smartmeal_save($1,0)',[JSON.stringify(streakHack)]);const loaded:any=(await db.query('select public.smartmeal_load() as result')).rows[0];assert.notEqual(loaded.result.data.firstUse,'2000-01-01');assert.notDeepEqual(loaded.result.data.streakDays,['2000-01-01']);
 await db.exec('reset role');
 const recipeId='00000000-0000-0000-0000-000000000003',recommendationId='00000000-0000-0000-0000-000000000004';
 await db.query('insert into public.smartmeal_recipes(id,user_id,payload) values($1,$2,$3)',[recipeId,bob,JSON.stringify({kind:'dish',name:'test-only'})]);
 await db.query("insert into public.smartmeal_recommendations(id,user_id,recipe_id,generated_at,meal_type,image_ready) values($1,$2,$3,'2026-10-03T01:00:00Z','Bữa chính',true)",[recommendationId,bob,recipeId]);
 await db.exec('set role authenticated');
 const valid={...loaded.result.data,occasions:[{id:'op',operationId:'op',date:'2026-10-03',slot:'Bữa sáng',dishes:[{id:'dish',recipeId,recommendationId,generatedAt:'2026-10-03T01:00:00Z'}]}]};
 await db.query('select public.smartmeal_save($1,1)',[JSON.stringify(valid)]);
 await assert.rejects(()=>db.query('select public.smartmeal_save($1,2)',[JSON.stringify({...valid,occasions:[{...valid.occasions[0],date:'2026-10-04'}]})]),/không cho sửa/);
 await db.query('select public.smartmeal_save($1,2)',[JSON.stringify({...valid,occasions:[]})]);
 await db.exec('reset role');
 await assert.rejects(()=>db.query('insert into public.smartmeal_catalog(payload,provenance) values($1,$2)',[JSON.stringify({kind:'combo',components:['1','2','3','4','5','6','7']}),'{}']),/catalog_combo_limit/);
 await assert.rejects(()=>db.query('insert into public.smartmeal_catalog(payload,provenance) values($1,$2)',[JSON.stringify({kind:'combo'}),'{}']),/catalog_combo_limit/);
 await db.query('insert into public.smartmeal_catalog(payload,provenance) values($1,$2)',[JSON.stringify({kind:'combo',components:['1','2','3','4','5','6']}),'{}']);
 await assert.rejects(()=>db.query("update public.smartmeal_accounts set data=jsonb_set(data,'{records}',$1) where user_id=$2",[JSON.stringify([{id:'bad',date:'2026-10-05',time:'08:00',duration:'Infinity'}]),bob]),/Thời lượng/);
 await db.close();
});
