import test from 'node:test';import assert from 'node:assert/strict';
import {classify,saveEaten,deleteEaten,dailyCount,validateRecord,upsertRecord,analyze,shiftDay,rank,streak,validDate,type Recipe,type Recommendation,type DigestiveRecord} from '../src/domain.ts';
const dishes:Recipe[]=['a','b','c'].map(id=>({id,name:id,description:'',category:'Rau',image:id,kind:'dish',ingredients:[id],seasonings:[],steps:[],nutrients:[],minutes:20}));
const recs:Recommendation[]=dishes.map(r=>({id:r.id,recipeId:r.id,generatedAt:'2026-10-02T09:59:00+07:00',mealType:'Bữa chính',imageReady:true}));
for(const [time,expected] of [['00:00','Bữa tối'],['02:29','Bữa tối'],['02:30','Bữa sáng'],['09:59','Bữa sáng'],['10:00','Bữa trưa'],['15:29','Bữa trưa'],['15:30','Bữa tối'],['23:59','Bữa tối']])test('PRD 1.1 boundary '+time,()=>assert.equal(classify(`2026-10-02T${time}:00+07:00`,'Bữa chính'),expected));
test('snack remains snack at any hour',()=>assert.equal(classify('2026-10-02T02:00:00+07:00','Ăn nhẹ'),'Ăn nhẹ'));
test('UTC is interpreted in HCM',()=>assert.equal(classify('2026-10-02T03:00:00Z','Bữa chính'),'Bữa trưa'));
test('invalid generation time cannot be classified',()=>assert.throws(()=>classify('bad','Bữa chính')));
test('three dishes save one occasion at original time, even on later eaten date',()=>{const result=saveEaten([],recs,dishes,'2026-10-03','op');assert.equal(result.length,1);assert.equal(result[0].slot,'Bữa sáng');assert.equal(result[0].dishes.length,3);assert.equal(result[0].dishes[0].generatedAt,recs[0].generatedAt);});
test('duplicate save operation is idempotent',()=>{const a=saveEaten([],recs,dishes,'2026-10-02','op');assert.deepEqual(saveEaten(a,recs,dishes,'2026-10-02','op'),a);});
test('delete middle then last updates count only once',()=>{let a=saveEaten([],recs,dishes,'2026-10-02','op');a=deleteEaten(a,'op:b');assert.deepEqual(a[0].dishes.map(d=>d.id),['op:a','op:c']);a=deleteEaten(a,'op:a');assert.equal(a.length,1);a=deleteEaten(a,'op:c');assert.equal(a.length,0);assert.equal(deleteEaten(a,'op:c').length,0);});
test('mixed meal types rejected',()=>assert.throws(()=>saveEaten([],[recs[0],{...recs[1],mealType:'Ăn nhẹ'}],dishes,'2026-10-02','op'),/riêng/));
test('incompatible main slots rejected',()=>assert.throws(()=>saveEaten([],[recs[0],{...recs[1],generatedAt:'2026-10-02T16:00:00+07:00'}],dishes,'2026-10-02','op'),/riêng/));
test('combo/component overlap blocks instead of double counting',()=>assert.throws(()=>saveEaten([],[recs[0],{...recs[1],recipeId:'combo'}],[...dishes,{...dishes[0],id:'combo',kind:'combo',components:['a','c']}],'2026-10-02','op'),/trùng/));
test('image incomplete is not a valid final result',()=>assert.throws(()=>saveEaten([],[{...recs[0],imageReady:false}],dishes,'2026-10-02','op')));
const record:DigestiveRecord={id:'1',date:'2026-10-02',time:'08:00',duration:3};
for(const duration of [0,-1,NaN,Infinity])test('invalid duration '+duration,()=>assert.ok(validateRecord({...record,duration})));
test('optional fields may all be missing',()=>assert.equal(validateRecord(record),undefined));
test('invalid actual calendar date rejected',()=>assert.equal(validDate('2026-02-30'),false));
test('editing record never increments; moving date updates counts',()=>{const records=upsertRecord([record],{...record,date:'2026-10-01'});assert.equal(records.length,1);assert.equal(dailyCount(records,'2026-10-02'),null);assert.equal(dailyCount(records,'2026-10-01'),1);});
test('missing not zero',()=>assert.equal(dailyCount([],'2026-10-02'),null));
test('three records and seven days permits current description',()=>{const records=[0,1,2].map(n=>({...record,id:String(n),date:shiftDay(record.date,-n)}));assert.equal(analyze(records,record.date,'2026-09-01').eligible,true);assert.equal(analyze(records,record.date,record.date).eligible,false);});
test('A8 requires both windows, coverage and per-field counts',()=>{const rs=Array.from({length:14},(_,i)=>({...record,id:String(i),date:shiftDay(record.date,-i),shape:4}));const a=analyze(rs,record.date,'2026-09-01');assert.equal(a.fieldEligible('shape'),true);assert.equal(a.fieldEligible('color'),false);assert.equal(analyze(rs.slice(0,7),record.date,'2026-09-01').fieldEligible('shape'),false);});
test('optional denominator excludes absent values',()=>{const a=analyze([record,{...record,id:'2',color:'Nâu'},{...record,id:'3',color:'Nâu'}],record.date,'2026-09-01');assert.deepEqual(a.color,[{label:'Nâu',count:2,percent:100}]);});
test('one calendar day contributes once and missed days reset',()=>{assert.equal(streak(['2026-10-01','2026-10-02','2026-10-02'],'2026-10-02'),2);assert.equal(streak(['2026-09-29'],'2026-10-02'),0);});
test('backup time boundaries and missing G',()=>{const ranked=rank(recs,[{...dishes[0],minutes:30},{...dishes[1],minutes:40},{...dishes[2],minutes:41}],30);assert.equal(ranked.length,2);assert.match(ranked[0].group,/Chưa đủ/);assert.equal(ranked[1].group,'Dự phòng');assert.equal(ranked[1].exceeded,10);});
test('G/B conflict and ties retain same group, no I tie-break',()=>{const r=rank([{...recs[0],goal:3,basic:1,ingredientUse:1},{...recs[1],goal:1,basic:3,ingredientUse:9},{...recs[2],goal:3,basic:1,ingredientUse:5}],dishes,30);assert.equal(new Set(r.map(x=>x.group)).size,1);});
