import {DistributionRing} from './DistributionRing';
import React from 'react';
import {Text,View} from 'react-native';
import {analyze,dayAt,shiftDay,type AppData,type DigestiveRecord} from './domain';
import {Card,Empty,Label,Title,palette,s} from './ui';
import {Eyebrow,f} from './Fresh';
export function DigestiveTrends({data}:{data:AppData}){
 const today=dayAt(),stats=analyze(data.records,today,data.firstUse);
 return <><Eyebrow>CHỈ TỪ NHẬT KÝ TIÊU HÓA</Eyebrow><Text style={f.display}>7 ngày{ '\n'}bạn đã ghi lại.</Text><Label small>{shiftDay(today,-6)} — {today}</Label>
  {!stats.current.length?<Empty title="Chưa có dữ liệu trong 7 ngày này" description="Các biểu đồ sẽ xuất hiện khi có bản ghi. Không suy đoán ngày trống là 0 lần."/>:<Card><Title>Thời gian</Title><Label small>Mỗi chấm là một bản ghi. Không nối qua những ngày thiếu dữ liệu.</Label><View style={{height:250,flexDirection:'row',gap:6}}><View style={{width:35,height:216,justifyContent:'space-between'}}>{['00:00','06:00','12:00','18:00','24:00'].map(t=><Text key={t} style={{fontSize:9,color:palette.muted}}>{t}</Text>)}</View>{Array.from({length:7},(_,i)=>{const d=shiftDay(today,i-6);return <View key={d} style={{flex:1,gap:8}}><View style={{height:210,borderLeftWidth:1,borderColor:'#E4E8F0'}}>{stats.current.filter(r=>r.date===d).map((r,index)=><View key={r.id} accessibilityLabel={`${d} ${r.time}`} style={{position:'absolute',left:3+(index%3)*6,top:(Number(r.time.slice(0,2))*60+Number(r.time.slice(3)))/1440*200,width:10,height:10,borderRadius:5,backgroundColor:palette.deepBlue}}/>)}</View><Text style={{fontSize:11,color:palette.muted,textAlign:'center'}}>{d.slice(-2)}</Text></View>;})}</View></Card>}
  {([{title:'Hình dạng',items:stats.shape,field:'shape'}, {title:'Thời lượng',items:stats.duration,field:'duration'}, {title:'Màu sắc',items:stats.color,field:'color'}] as const).map(({title,items,field})=><Card key={title}><View style={[s.row,{justifyContent:'space-between'}]}><Title>{title}</Title><Label small>{items.reduce((n,x)=>n+x.count,0)} bản ghi có dữ liệu</Label></View>{!stats.eligible||!items.length?<Label>Chưa đủ dữ liệu để mô tả phân bố.</Label>:field!=='duration'?<DistributionRing items={items}/>:items.map((item,index)=><View key={item.label} style={{gap:6}}><View style={[s.row,{justifyContent:'space-between'}]}><Label>{item.label}{field==='duration'?' phút':''}</Label><Label small>{item.count} · {Math.round(item.percent)}%</Label></View><View style={{height:12,borderRadius:8,backgroundColor:'#EDF0F4'}}><View style={{height:12,borderRadius:8,width:`${item.percent}%`,backgroundColor:['#9DBAB4','#B3BDD5','#C3CEA9','#D4BD9C'][index%4]}}/></View></View>)}{field==='duration'&&stats.eligible&&stats.average!=null&&<Label>Trung bình {stats.average.toFixed(1)} phút</Label>}<Label small>{stats.fieldEligible(field as keyof DigestiveRecord)?'Trường này đủ độ phủ để so sánh hai cửa sổ. Nội dung diễn giải kiểm chứng chưa được cấu hình.':'Chưa đủ độ phủ để so sánh với 7 ngày trước.'}</Label></Card>)}
  <View style={{flexDirection:'row',gap:12,alignItems:'stretch'}}><Card style={{flex:1,padding:14,aspectRatio:1,minHeight:175,backgroundColor:'#EEE7F6'}}><Text style={{fontSize:16,fontWeight:'700',color:palette.ink}}>Tổng kết</Text><Label small>{stats.current.length} bản ghi trên {new Set(stats.current.map(r=>r.date)).size} ngày.</Label><Label small>{stats.eligible?'Tỷ lệ tính theo bản ghi có dữ liệu từng trường.':'Chưa đủ dữ liệu để mô tả phân bố.'}</Label></Card><Card style={{flex:1,padding:14,aspectRatio:1,minHeight:175}}><Text style={{fontSize:16,fontWeight:'700',color:palette.ink}}>Gợi ý từ SmartMeal</Text><Label small>Nội dung hướng dẫn có nguồn kiểm chứng đang chờ bổ sung.</Label></Card></View><Label small>Thông tin còn thiếu không phải kết quả bình thường hay bất thường. Đây không phải chẩn đoán.</Label>
 </>;
}
