import React from 'react';
import {View,Text,Pressable} from 'react-native';
import {dayAt,shiftDay,SHAPES,type DigestiveRecord} from './domain';
import {Button,Card,Empty,Label,SwipeRow,Title,palette,s} from './ui';
import {StoolGlyph} from './ObservationChoices';
export function DigestiveHistory({records,onAdd,onOpen,onEdit,onDelete}:{records:DigestiveRecord[];onAdd:()=>void;onOpen:(r:DigestiveRecord)=>void;onEdit:(r:DigestiveRecord)=>void;onDelete:(r:DigestiveRecord)=>void}){
 const today=dayAt(),start=shiftDay(today,-6),week=records.filter(r=>r.date>=start&&r.date<=today);
 const sorted=[...records].sort((a,b)=>(b.date+b.time).localeCompare(a.date+a.time));
 const dates=[...new Set(sorted.map(r=>r.date))];
 return <><Card style={{backgroundColor:'#63517D'}}><Text style={{color:'#EEE3FB',fontSize:11,fontWeight:'700'}}>TIÊU HÓA TUẦN NÀY</Text><Text style={{color:'white',fontSize:30,fontWeight:'800'}}>{week.length?`${week.length} bản ghi`:'Chưa ghi nhận'}</Text><Text style={{color:'#E1D4ED',fontSize:12}}>{start.split('-').reverse().join('/')} — {today.split('-').reverse().join('/')}</Text><View style={{flexDirection:'row',gap:6,marginTop:10}}>{Array.from({length:7},(_,i)=>{const d=shiftDay(start,i),n=week.filter(r=>r.date===d).length;return <View key={d} style={{flex:1,alignItems:'center',gap:7}}><Text style={{color:'#E4D8EF',fontSize:10}}>{['CN','T2','T3','T4','T5','T6','T7'][new Date(d+'T12:00:00Z').getUTCDay()]}</Text><View style={{width:30,height:30,borderRadius:15,backgroundColor:n?'#DCC7F0':'#78658D',justifyContent:'center',alignItems:'center'}}><Text style={{color:n?'#49375F':'#F2E9FC',fontSize:12}}>{n>1?n:n?'✓':'—'}</Text></View></View>;})}</View></Card><Button title="＋ Thêm bản ghi" onPress={onAdd}/>{dates.map(date=><View key={date} style={{gap:10}}><View style={[s.row,{justifyContent:'space-between'}]}><Text style={{fontWeight:'700',color:palette.ink}}>{date===today?'Hôm nay':date===shiftDay(today,-1)?'Hôm qua':'Ngày cũ hơn'} · {date.split('-').reverse().join('/')}</Text><Label small>{sorted.filter(r=>r.date===date).length} lần</Label></View>{sorted.filter(r=>r.date===date).map(r=><SwipeRow key={r.id} onDelete={()=>onDelete(r)} contentStyle={{backgroundColor:'white',padding:16}}><View style={[s.row,{alignItems:'flex-start'}]}><Pressable accessibilityRole="button" accessibilityLabel={`Xem bản ghi ${r.time}`} onPress={()=>onOpen(r)} style={{flex:1,flexDirection:'row',gap:10}}><View style={{backgroundColor:'#EEE3F7',borderRadius:24,width:44,height:44}}><StoolGlyph shape={r.shape}/></View><View style={{flex:1,gap:3}}><Text style={{fontSize:19,fontWeight:'700',color:palette.ink}}>{r.time}</Text><Text style={{fontSize:11,color:palette.primary}}>{r.shape?`Bristol loại ${r.shape}`:'Chưa ghi nhận hình dạng'}</Text><Label small>{r.shape?SHAPES[r.shape-1]:''} · {Number.isFinite(r.duration)&&r.duration>0?`${r.duration} phút`:'Chưa ghi nhận thời lượng'}</Label></View></Pressable><Pressable accessibilityRole="button" accessibilityLabel={`Sửa bản ghi ${r.time}`} onPress={()=>onEdit(r)} style={{padding:9,borderRadius:18,backgroundColor:'#F0EAF6'}}><Text style={{fontSize:12,color:palette.primary}}>Sửa</Text></Pressable></View><View style={{flexDirection:'row',flexWrap:'wrap',gap:6,marginTop:12}}>{[r.color,r.feeling,r.amount].filter(Boolean).map((label,i)=><View key={i} style={{paddingHorizontal:9,paddingVertical:4,borderRadius:12,backgroundColor:'#F1ECF6'}}><Text style={{fontSize:11,color:palette.ink}}>{label}</Text></View>)}</View></SwipeRow>)}</View>)}{!records.length&&<Empty title="Chưa có bản ghi" description="Nhấn dấu cộng để ghi lại lần đầu."/>}</>;
}
