import {FoodImage} from './FoodImage';
import React,{useState} from 'react';
import {View,Text,Image,Pressable,TextInput} from 'react-native';
import {Chips,Empty,Label,SwipeRow,palette,s} from './ui';
import {Eyebrow,Icon,f} from './Fresh';
import {recipeUpdate,verifiedNutrients,type Recipe} from './domain';
export function Notebook({catalog,saved,width,onOpen,onDelete,onUpdate,imageFor,mode,setMode,filter,setFilter,search,setSearch}:{mode:'dish'|'combo';setMode:(v:'dish'|'combo')=>void;filter:string;setFilter:(v:string)=>void;search:string;setSearch:(v:string)=>void;onUpdate:(oldId:string,nextId:string)=>void;catalog:Recipe[];saved:string[];width:number;onOpen:(id:string)=>void;onDelete:(id:string)=>void;imageFor:(r:Recipe)=>any}){
 const cardWidth=(width-40-14)/2;
 const items=catalog.filter(r=>saved.includes(r.id)&&r.kind===mode&&(mode==='combo'||!filter||r.category===filter)&&(!search||(r.name+' '+r.ingredients.join(' ')+' '+verifiedNutrients(r).join(' ')).toLocaleLowerCase('vi').includes(search.toLocaleLowerCase('vi'))));
 return <View style={{gap:20}}><View style={{gap:8}}><Eyebrow>BỘ SƯU TẬP CỦA BẠN</Eyebrow><Text style={f.display}>Món ngon,{ '\n'}để dành lần tới.</Text><Label small>{saved.length} mục đã lưu · Chưa có nghĩa là đã ăn</Label></View>
  <View style={[s.row,{borderRadius:20,backgroundColor:'white',paddingHorizontal:16}]}><Icon name="search" size={20}/><TextInput accessibilityLabel="Tìm trong Sổ tay" value={search} onChangeText={setSearch} placeholder="Tên món, nguyên liệu…" placeholderTextColor={palette.muted} style={{flex:1,minHeight:52,color:palette.ink,fontSize:15}}/></View>
  <View style={{flexDirection:'row',backgroundColor:'#E8EEDB',padding:5,borderRadius:19}}>{(['dish','combo'] as const).map(k=><Pressable key={k} accessibilityRole="button" accessibilityState={{selected:mode===k}} onPress={()=>setMode(k)} style={{flex:1,padding:12,alignItems:'center',borderRadius:14,backgroundColor:mode===k?'white':'transparent'}}><Text style={[s.text,{fontWeight:'700'}]}>{k==='dish'?'Món đơn':'Combo'}</Text></Pressable>)}</View>
  {mode==='dish'&&<Chips items={['Thịt','Trứng','Hải sản','Rau','Tinh bột','Hoa quả']} value={filter} onChange={setFilter}/>}
  <View style={{flexDirection:'row',flexWrap:'wrap',gap:14}}>{items.map(p=><View key={p.id} style={{width:mode==='dish'?cardWidth:'100%'}}><SwipeRow onDelete={()=>onDelete(p.id)} contentStyle={{padding:0,backgroundColor:'white'}}><Pressable accessibilityRole="button" accessibilityLabel={'Xem '+p.name} onPress={()=>onOpen(p.id)} style={{gap:12,padding:12,flexDirection:mode==='dish'?'column':'row'}}><FoodImage source={imageFor(p)} style={{width:mode==='dish'?'100%':104,height:mode==='dish'?cardWidth-24:112,borderRadius:18,resizeMode:'cover'}}/><View style={{flex:1,gap:5}}><Text style={[s.text,{fontWeight:'800',fontSize:16,lineHeight:21}]}>{p.name}</Text><Text style={s.small}>{p.description}</Text><Label small>{p.minutes} phút</Label>{!!verifiedNutrients(p).length&&<Text style={[s.small,{color:palette.primary,fontWeight:'600'}]}>{verifiedNutrients(p)[0]}</Text>}</View></Pressable>{recipeUpdate(p,catalog)&&<Pressable accessibilityRole="button" onPress={()=>onUpdate(p.id,recipeUpdate(p,catalog)!.id)} style={{padding:12}}><Text style={{color:palette.primary,fontWeight:'700'}}>Cập nhật công thức</Text></Pressable>}</SwipeRow></View>)}</View>
  {!items.length&&<Empty title={search||filter?'Chưa tìm thấy món phù hợp':'Chừa chỗ cho món bạn thích'} description={search||filter?'Thử từ khóa hoặc nhóm nguyên liệu khác.':'Nhấn Lưu vào Sổ tay trên kết quả AI để bắt đầu bộ sưu tập.'}/>}
 </View>;
}
