import {pyramidDrag} from './pyramidMotion';
import React,{useEffect,useRef,useState} from 'react';
import {AccessibilityInfo,Animated,Image,Modal,PanResponder,Platform,Pressable,ScrollView,Text,View,useWindowDimensions} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
import {LinearGradient} from 'expo-linear-gradient';
import {BackButton} from './BackButton';
import {Button,Label,Title,palette,s} from './ui';
const artwork=require('../assets/brand/pyramid-3d.png');
// Image-space bands describe this illustration only, never a dietary prescription.
const bands=[{top:.04,end:.29,width:.3,items:'Bánh ngọt, kẹo, dầu ăn'},{top:.29,end:.445,width:.44,items:'Trứng, cá, thịt'},{top:.445,end:.61,width:.57,items:'Sữa, sữa chua, phô mai'},{top:.61,end:.77,width:.71,items:'Rau và trái cây'},{top:.77,end:.95,width:.87,items:'Cơm, bánh mì, ngô, khoai'}];

export function Pyramid({full=false,onOpen:_onOpen}:{full?:boolean;onOpen?:()=>void}){
 const screen=useWindowDimensions(),anchor=useRef<View>(null);
 const [open,setOpen]=useState(false),[selected,setSelected]=useState<number|null>(null),[reduced,setReduced]=useState(true);
 const [rect,setRect]=useState({x:0,y:100,width:screen.width,height:450});
 const expand=useRef(new Animated.Value(0)).current,drag=useRef(new Animated.Value(0)).current;
 const reducedRef=useRef(reduced);reducedRef.current=reduced;
 const [artWidth,setArtWidth]=useState(300);
 const pointer=useRef<{id:number;y:number}|null>(null);
 useEffect(()=>{void AccessibilityInfo.isReduceMotionEnabled().then(setReduced);const h=AccessibilityInfo.addEventListener('reduceMotionChanged',setReduced);return()=>{h.remove();expand.stopAnimation();drag.stopAnimation();};},[]);
 const move=(delta:number)=>drag.setValue(pyramidDrag(delta));
 const release=()=>{if(reducedRef.current)drag.setValue(0);else Animated.spring(drag,{toValue:0,stiffness:210,damping:22,mass:.9,useNativeDriver:false}).start();};
 const responder=useRef(PanResponder.create({onMoveShouldSetPanResponder:(_,g)=>Math.abs(g.dy)>8,onPanResponderGrant:()=>drag.stopAnimation(),onPanResponderMove:(_,g)=>move(g.dy),onPanResponderRelease:release,onPanResponderTerminate:release})).current;
 const show=()=>anchor.current?.measureInWindow((x,y,width,height)=>{setRect({x,y,width,height});expand.setValue(0);setOpen(true);});
 const close=()=>{Animated.timing(expand,{toValue:0,duration:reduced?0:260,useNativeDriver:false}).start(()=>{setOpen(false);setSelected(null);});};
 const visual=(detail:boolean)=><View onLayout={e=>setArtWidth(e.nativeEvent.layout.width)} style={{width:'100%'}}><Image source={artwork} resizeMode="contain" style={{width:'100%',aspectRatio:1.5}}/>{detail&&bands.map((b,i)=><Pressable key={i} accessibilityRole="button" accessibilityLabel={`Xem minh họa tầng ${i+1}: ${b.items}`} accessibilityState={{selected:selected===i}} onPress={()=>setSelected(i)} style={{position:'absolute',top:`${b.top*100}%`,height:`${(b.end-b.top)*100}%`,width:`${b.width*100}%`,left:`${(1-b.width)*50}%`,borderRadius:12,borderWidth:selected===i?2:0,borderColor:'#A789C6',backgroundColor:selected===i?'rgba(229,218,245,.3)':'transparent'}}/>)}</View>;
 const detail=<><Title>Tháp dinh dưỡng</Title><Label small>Chạm từng tầng để xem thực phẩm minh họa.</Label>{visual(true)}{selected!==null&&<View style={{padding:20,borderRadius:24,backgroundColor:'rgba(255,255,255,.82)',borderWidth:1,borderColor:'white',boxShadow:'0px 12px 32px rgba(81,57,112,.1)',...(Platform.OS==='web'?{backdropFilter:'blur(18px)'}:{})}}><Title>Tầng {selected+1}</Title><View style={{height:Math.max(70,artWidth/1.5*(bands[selected].end-bands[selected].top)),overflow:'hidden',borderRadius:16}}><Image source={artwork} resizeMode="contain" style={{position:'absolute',width:artWidth,height:artWidth/1.5,top:-artWidth/1.5*bands[selected].top,alignSelf:'center'}}/></View><Label>{bands[selected].items}</Label><Button title="Đóng tầng đang xem" quiet onPress={()=>setSelected(null)}/></View>}<Label small>Hình minh họa theo mẫu thiết kế; chưa phải hướng dẫn khẩu phần hoặc khuyến nghị dinh dưỡng đã kiểm chứng.</Label></>;
 const sculpture=<Animated.View style={{height:drag.interpolate({inputRange:[-100,0,100],outputRange:[210,270,340]}),justifyContent:'center',transform:[{perspective:900},{rotateX:drag.interpolate({inputRange:[-100,100],outputRange:reduced?['0deg','0deg']:['-12deg','12deg']})},{rotateZ:drag.interpolate({inputRange:[-100,100],outputRange:reduced?['0deg','0deg']:['-5deg','5deg']})}]}}>{visual(false)}</Animated.View>;
 if(full)return <View style={{gap:20}}>{detail}</View>;
 return <><View ref={anchor} collapsable={false}><LinearGradient colors={['#3F3556','#615174','#353047']} style={{borderRadius:28,padding:24,gap:16,overflow:'hidden'}}><Text style={{color:'#DED2EE',fontSize:10,letterSpacing:1.4}}>KHÁM PHÁ DINH DƯỠNG</Text>{Platform.OS==='web'?<div aria-label="Kéo dọc để xoay tháp" style={{touchAction:'pan-x',userSelect:'none',cursor:'grab'}} onPointerDown={e=>{pointer.current={id:e.pointerId,y:e.clientY};drag.stopAnimation();e.currentTarget.setPointerCapture(e.pointerId);}} onPointerMove={e=>{if(pointer.current?.id===e.pointerId)move(e.clientY-pointer.current.y);}} onPointerUp={()=>{pointer.current=null;release();}} onPointerCancel={()=>{pointer.current=null;release();}}>{sculpture}</div>:<View {...responder.panHandlers}>{sculpture}</View>}<Text style={{color:'white',fontSize:31,lineHeight:39,fontWeight:'600'}}>Hiểu bữa ăn.{'\n'}Chọn điều phù hợp.</Text><Text style={{color:'#DFD6E8',lineHeight:22,fontSize:13}}>Kéo dọc để khám phá · Mở để xem từng tầng</Text><Button title="Xem chi tiết tháp" onPress={show}/></LinearGradient></View><Modal transparent visible={open} animationType="none" onRequestClose={close} onShow={()=>Animated.timing(expand,{toValue:1,duration:reduced?0:380,useNativeDriver:false}).start()}><View style={{flex:1,backgroundColor:'rgba(40,28,60,.2)'}}><Animated.View style={{position:'absolute',overflow:'hidden',backgroundColor:'#F3EDF9',top:expand.interpolate({inputRange:[0,1],outputRange:[rect.y,0]}),left:expand.interpolate({inputRange:[0,1],outputRange:[rect.x,0]}),width:expand.interpolate({inputRange:[0,1],outputRange:[rect.width,screen.width]}),height:expand.interpolate({inputRange:[0,1],outputRange:[rect.height,screen.height]}),borderRadius:expand.interpolate({inputRange:[0,1],outputRange:[28,0]})}}><SafeAreaView style={{flex:1}}><BackButton onPress={close}/><ScrollView contentContainerStyle={{padding:24,gap:20,width:'100%',maxWidth:640,alignSelf:'center'}}>{detail}</ScrollView></SafeAreaView></Animated.View></View></Modal></>;
}
