import {MotionPressable} from './MotionPressable';
import React,{useRef,useState} from 'react';
import {View,Text,Pressable,TextInput,StyleSheet,Image,PanResponder,Animated,type ViewStyle} from 'react-native';
export const palette={ink:'#302D3D',primary:'#79619E',green:'#DCEACF',yellow:'#F6E9C6',cream:'#F8F7FB',lime:'#DCE99F',blue:'#DDEAF4',deepBlue:'#4A7191',muted:'#767080'};
export function Label({children,small=false}:{children:React.ReactNode;small?:boolean}){return <Text style={small?s.small:s.text}>{children}</Text>;}
export function Title({children}:{children:React.ReactNode}){return <Text style={s.title}>{children}</Text>;}
export function Card({children,style}:{children:React.ReactNode;style?:ViewStyle}){return <View style={[s.card,style]}>{children}</View>;}
export function Button({title,onPress,quiet=false,disabled=false}:{title:string;onPress:()=>void;quiet?:boolean;disabled?:boolean}){return <MotionPressable accessibilityRole="button" accessibilityLabel={title} disabled={disabled} onPress={onPress} style={[s.button,...(quiet?[s.quiet]:[]),...(disabled?[{opacity:0.55}]:[])]}><Text style={[s.buttonText,quiet&&{color:palette.ink}]}>{title}</Text></MotionPressable>;}
export function Input({label,value,onChange,number=false,secure=false,placeholder, multiline=false}:{label:string;value:string;onChange:(s:string)=>void;number?:boolean;secure?:boolean;placeholder?:string;multiline?:boolean}){return <View style={{gap:7,marginVertical:7}}><Label small>{label}</Label><TextInput accessibilityLabel={label} value={value} onChangeText={onChange} keyboardType={number?'decimal-pad':'default'} secureTextEntry={secure} placeholder={placeholder} placeholderTextColor="#86917E" multiline={multiline} style={[s.input,multiline&&{minHeight:82,textAlignVertical:'top'}]}/></View>;}
export function Chips({items,value,onChange}:{items:string[];value?:string;onChange:(v:string)=>void}){return <View style={s.wrap}>{items.map(item=><Pressable key={item} accessibilityRole="button" accessibilityState={{selected:value===item}} onPress={()=>onChange(value===item?'':item)} style={[s.chip,value===item&&{backgroundColor:palette.green,borderColor:palette.ink}]}><Text style={s.text}>{item}</Text></Pressable>)}</View>;}
export function Empty({title,description}:{title:string;description:string}){return <Card style={{paddingVertical:40,alignItems:'center'}}><Text style={{fontSize:36}}>◇</Text><Title>{title}</Title><Label small>{description}</Label></Card>;}
export function SwipeRow({children,onDelete,contentStyle,hideHint=false}:{children:React.ReactNode;onDelete:()=>void;contentStyle?:ViewStyle;hideHint?:boolean}){
 const x=useRef(new Animated.Value(0)).current;const [open,setOpen]=useState(false);
 const move=(v:boolean)=>{setOpen(v);Animated.spring(x,{toValue:v?-76:0,useNativeDriver:false}).start();};
 const responder=useRef(PanResponder.create({onMoveShouldSetPanResponder:(_,g)=>Math.abs(g.dx)>12&&Math.abs(g.dx)>Math.abs(g.dy),onPanResponderMove:(_,g)=>x.setValue(Math.max(-76,Math.min(0,g.dx))),onPanResponderRelease:(_,g)=>move(g.dx<-30)})).current;
 return <View style={{overflow:'hidden',borderRadius:22,marginVertical:5,backgroundColor:'#F5DFDF'}}><Pressable accessibilityRole="button" accessibilityLabel="Xóa bản ghi" disabled={!open} onPress={()=>{move(false);onDelete();}} style={{position:'absolute',right:0,top:0,bottom:0,width:76,alignItems:'center',justifyContent:'center',borderRadius:22}}><View style={{width:20,height:24,borderWidth:2,borderColor:'#A65D5D',borderRadius:4}}><View style={{position:'absolute',top:-6,left:-4,width:24,height:2,backgroundColor:'#A65D5D'}}/><View style={{position:'absolute',top:-10,left:4,width:8,height:2,backgroundColor:'#A65D5D'}}/></View></Pressable><Animated.View {...responder.panHandlers} accessibilityActions={[{name:'activate',label:'Hiện thao tác xóa'}]} onAccessibilityAction={()=>move(!open)} style={[{transform:[{translateX:x}],backgroundColor:palette.cream,borderRadius:22,padding:14},contentStyle]}><View pointerEvents={open?'none':'auto'}>{children}</View>{!hideHint&&<Pressable accessibilityRole="button" accessibilityLabel={open?'Đóng thao tác xóa':'Hiện thao tác xóa'} onPress={()=>move(!open)} style={{alignSelf:'flex-end',padding:8}}><Text style={s.small}>{open?'Đóng':'•••'}</Text></Pressable>}</Animated.View></View>;
}
export const s=StyleSheet.create({
 root:{flex:1,backgroundColor:palette.cream},page:{padding:20,gap:24,paddingBottom:36},row:{flexDirection:'row',alignItems:'center',gap:12},wrap:{flexDirection:'row',flexWrap:'wrap',gap:8},header:{paddingHorizontal:20,paddingTop:14,paddingBottom:12,backgroundColor:'transparent'},title:{fontSize:22,lineHeight:28,fontWeight:'600',letterSpacing:-0.7,color:palette.ink,marginVertical:4},text:{fontSize:15,lineHeight:23,color:palette.ink},small:{fontSize:12,lineHeight:19,color:palette.muted},card:{backgroundColor:'rgba(255,255,255,0.82)',borderRadius:26,padding:22,gap:12,borderWidth:1,borderColor:'rgba(255,255,255,0.96)',boxShadow:'0px 8px 30px rgba(48,45,61,0.045)'},button:{minHeight:47,paddingHorizontal:16,paddingVertical:12,borderRadius:24,backgroundColor:palette.ink,alignItems:'center',justifyContent:'center'},quiet:{backgroundColor:'#EEE9F5'},buttonText:{fontSize:15,color:'white',fontWeight:'700'},input:{minHeight:48,borderRadius:14,backgroundColor:'#F5F3F9',padding:13,color:palette.ink,fontSize:16,borderWidth:1,borderColor:'#E9E4EF'},chip:{paddingHorizontal:12,paddingVertical:8,borderRadius:13,borderWidth:1,borderColor:'#E7ECDf',backgroundColor:'#FAFBF7'},nav:{flexDirection:'row',margin:12,marginTop:0,backgroundColor:'rgba(255,255,255,.94)',borderRadius:26,padding:5,boxShadow:'0px 4px 24px rgba(35,60,53,.09)'},navItem:{flex:1,alignItems:'center',justifyContent:'center',minHeight:59,borderRadius:21,gap:3},overlay:{flex:1,backgroundColor:'rgba(26,35,20,.48)',alignItems:'center',justifyContent:'center',padding:20},dialog:{width:'100%',maxWidth:500,backgroundColor:palette.cream,borderRadius:28,padding:22,gap:16,maxHeight:'90%'},error:{color:'#A33036',fontSize:14,lineHeight:20},badge:{backgroundColor:palette.yellow,padding:7,borderRadius:9,alignSelf:'flex-start'},hero:{width:'100%',height:210,borderRadius:22,resizeMode:'contain'},divider:{height:1,backgroundColor:'#E8ECDf',marginVertical:8}
});
