// Completes the existing prototype; account operations below are explicitly local demonstrations.
let profileData={name:'[Tên người dùng]',goal:'',taste:'',age:'',gender:'',height:'',weight:'',time:'',kind:'main',benefits:''},profileDraft={},goalLog=[],goalAsked='2026-09-20';
let accountOrigin='home',accountScroll=0,accountMode='entry',auditOffline=false,streakState={count:0,days:[]};
const profileComplete=()=>!!profileData.goal.trim()&&!!profileData.taste.trim();
const auditContinue=()=>'<button class="account-continue" data-audit="profile">Tiếp tục</button>';
function accountHeader(title){return '<header class="record-head"><button data-audit="account-back" aria-label="Quay lại">'+emoji('back')+'</button><h2>'+title+'</h2></header>';}
function openAccount(mode='entry',origin='home'){accountOrigin=origin;accountScroll=history.scrollTop;accountMode=mode;page.hidden=false;overlay.hidden=true;renderAccount();}
function accountBack(){if(accountOrigin==='ai'){page.hidden=true;history.scrollTop=accountScroll;}else if(accountOrigin==='saved')savedOpen();else if(accountOrigin==='record')recordOpen('entry');else show('home');}
function renderAccount(){
 let content='';const note='<p class="audit-notice">Bản thử luồng · chưa kết nối xác thực. Không nhập mật khẩu thật.</p>';
 if(accountMode==='entry')content='<button class="account-main" data-audit="auth-login">Đăng nhập</button><button class="account-main" data-audit="auth-register">Đăng ký</button>';
 if(['login','register','reset'].includes(accountMode)){content='<form id="audit-auth-form"><label>Email<input type="email" required autocomplete="off" placeholder="Email mẫu"></label>'+(accountMode==='reset'?'':'<label>Mật khẩu<input type="password" required autocomplete="off" placeholder="Mật khẩu mẫu"></label>')+'<p class="account-error" role="alert"></p><button class="account-main" type="submit">'+({login:'Đăng nhập',register:'Đăng ký',reset:'Gửi liên kết đặt lại'})[accountMode]+'</button></form>'+(accountMode==='login'?'<button data-audit="auth-reset">Quên mật khẩu</button>':'');}
 if(accountMode==='verify')content='<p>[Xác minh email qua liên kết được gửi đến địa chỉ đăng ký]</p><button class="account-main" data-audit="verified">Mô phỏng đã xác minh email</button>';
 if(accountMode==='reset-sent')content='<p>[Liên kết đặt lại mật khẩu sẽ được gửi qua email]</p><button data-audit="auth-login">Về đăng nhập</button>';
 if(accountMode==='logout')content='<p>Đăng xuất tài khoản?</p><button class="account-main" data-audit="logout">Đăng xuất</button><button data-audit="account-back">Quay lại</button>';
 if(accountMode==='delete-account')content='<p>Yêu cầu xóa tài khoản và dữ liệu hồ sơ, Nhật ký, Sổ tay, Ghi lại liên quan.</p><p>[Thời gian xử lý và quy trình xác minh: chờ chính sách chính thức]</p><button disabled>Chờ kết nối xử lý yêu cầu</button>';
 const titles={entry:'Tài khoản',login:'Đăng nhập',register:'Đăng ký',reset:'Đặt lại mật khẩu',verify:'Xác minh email','reset-sent':'Kiểm tra email',logout:'Đăng xuất','delete-account':'Xóa tài khoản'};
 page.innerHTML='<div class="account-shell">'+accountHeader(titles[accountMode])+ '<main class="account-content">'+note+content+'</main></div>';q('#sm-caption').textContent='Luồng tài khoản theo PRD v0.9 · Khung chức năng NHÁP; thiếu màn hình tài khoản gốc để đối chiếu. Chỉ mô phỏng, không xác thực thật.';
}
pendingAccount=function(action){openAccount(action==='Đăng xuất'?'logout':action==='Đăng ký'?'register':'login','ai');};
function openProfile(origin='home'){accountOrigin=origin;profileDraft={...profileData};page.hidden=false;renderProfile();}
function renderProfile(){const fields=[['name','Tên hiển thị'],['age','Tuổi'],['gender','Giới tính'],['height','Chiều cao (cm)'],['weight','Cân nặng (kg)'],['goal','Mục tiêu dinh dưỡng *'],['time','Thời gian nấu (phút)'],['benefits','Lợi ích mong muốn']];page.innerHTML='<div class="account-shell">'+accountHeader('Thông tin tài khoản')+'<main class="account-content"><p class="audit-notice">Hồ sơ mẫu · bố cục chờ đối chiếu màn hình gốc</p><p>Chiều cao và cân nặng chỉ dùng tính BMI tham khảo. Tuổi, giới tính chưa dùng để xếp hạng món.</p>'+fields.map(([key,label])=>'<label>'+label+'<input data-profile="'+key+'" value="'+escapeRecord(profileDraft[key])+'" '+(['age','height','weight','time'].includes(key)?'type="number" min="0"':'')+'></label>').join('')+'<label>Khẩu vị *<select data-profile="taste"><option value="">Chưa chọn</option>'+['Thanh đạm','Đậm đà','Trung tính'].map(v=>'<option '+(profileDraft.taste===v?'selected':'')+'>'+v+'</option>').join('')+'</select></label><label>Loại bữa<select data-profile="kind"><option value="main">Bữa chính</option><option value="snack" '+(profileDraft.kind==='snack'?'selected':'')+'>Ăn nhẹ</option></select></label><p class="account-error" role="alert"></p><button data-audit="delete-account">Yêu cầu xóa tài khoản</button></main><footer><button class="account-main" data-audit="save-profile">Lưu</button></footer></div>';}
function saveProfile(){if(!profileDraft.goal.trim()||!profileDraft.taste.trim()){q('.account-error').textContent='Hãy điền mục tiêu dinh dưỡng và chọn khẩu vị.';return false;}goalLog=AuditModel.changeGoal(goalLog,profileData.goal,profileDraft.goal,recordToday);profileData={...profileDraft};goalAsked=recordToday;return true;}
function requireProfile(origin){if(authState==='guest'){openAccount('entry',origin);return false;}if(!profileComplete()){openProfile(origin);q('.account-error').textContent='Hoàn tất mục tiêu dinh dưỡng và khẩu vị để tiếp tục.';return false;}return true;}
function auditDialog(title,body,buttons){const layer=document.createElement('div');layer.className='audit-overlay';layer.innerHTML='<section role="dialog" aria-modal="true" aria-label="'+title+'"><h3>'+title+'</h3><p>'+body+'</p>'+buttons.map(([action,label])=>'<button data-audit="'+action+'">'+label+'</button>').join('')+'</section>';q('.sm-phone').append(layer);page.inert=true;q('.sm-ai').inert=true;layer.querySelector('button').focus();}
function closeAuditDialog(){q('.audit-overlay')?.remove();page.inert=false;syncCoveredChat();}
function enterDemoDay(date=recordToday){const r=AuditModel.streak(streakState,date,authState==='member'&&profileComplete());streakState=r.state;if(r.show){streakEntry();q('.hp-streak-page strong').textContent=streakState.count;q('.hp-streak-page .hp-placeholder').textContent=streakState.days.join(' · ');}else show('home');}
const beforeAuditHome=renderHome;
renderHome=function(){beforeAuditHome();q('.hp-screen').classList.add('audit-home');q('.hp-rabbit')?.remove();
 const account=q('.hp-account');if(authState==='guest'){account.outerHTML='<button class="account-continue account-signedout" data-audit="auth-entry">Đăng nhập/Đăng ký →</button>';}else{account.querySelector('strong').textContent=profileData.name||'[Tên chưa thiết lập]';if(!profileComplete())account.insertAdjacentHTML('afterend',auditContinue());}
 const tiles=[...q('.hp-grid').children];const bowel=tiles[3];const btn=document.createElement('button');btn.className=bowel.className+' home-bowel';btn.dataset.audit='bowel';btn.innerHTML=bowel.innerHTML;btn.setAttribute('aria-label','Hôm nay đi tiêu — mở Ghi lại');bowel.replaceWith(btn);
 const bmi=tiles[0];const missing=[!Number(profileData.height)?'chiều cao':'',!Number(profileData.weight)?'cân nặng':''].filter(Boolean);bmi.querySelector('.hp-value').textContent=missing.length?'Chưa tính BMI':(Number(profileData.weight)/(Number(profileData.height)/100)**2).toFixed(1);bmi.querySelector('.hp-placeholder').textContent=missing.length?'Thiếu '+missing.join(' và '):'[Biểu đồ BMI — thiết kế sau]';
 const changes=goalLog.filter(r=>AuditModel.day(recordToday)-AuditModel.day(r.date)<=30&&r.from&&r.from!==r.to);tiles[2].querySelector('.hp-placeholder').textContent=changes.length?changes.map(r=>r.date+': '+r.from+' → '+r.to).join(' · '):'Chưa có thay đổi được ghi nhận';
 q('.hp-flame>span:last-child').textContent=authState==='member'&&streakState.count?streakState.count:'—';q('.hp-flame').setAttribute('aria-label','Chuỗi ngày sử dụng '+(streakState.count||'chưa ghi nhận'));q('.hp-content').textContent='[Nội dung dinh dưỡng ngày '+recordToday+' — chờ nội dung được duyệt]';
 q('#sm-caption').textContent='Hồ sơ · NHÁP / CHƯA PHÊ DUYỆT. Nền kem, các thẻ trắng, điểm nhấn xanh/vàng. Ô đi tiêu mở Ghi lại; dữ liệu mẫu.';
 if(authState==='member'&&profileComplete()&&AuditModel.day(recordToday)-AuditModel.day(goalAsked)>=7&&!q('.audit-overlay'))auditDialog('Mục tiêu dinh dưỡng','Bạn có muốn thay đổi mục tiêu cho 7 ngày tiếp theo?',[['goal-keep','Giữ nguyên'],['goal-change','Thay đổi'],['goal-skip','Bỏ qua']]);
};
const beforeAuditSaved=renderSaved;renderSaved=function(){beforeAuditSaved();if(authState==='member'&&!profileComplete())q('.saved-title').insertAdjacentHTML('beforeend',auditContinue());q('.saved-top input').insertAdjacentHTML('beforebegin','<span class="saved-search-mascot" aria-label="Vị trí Bạn Dài gốc">[Bạn Dài]</span>');};
const beforeAuditRecord=renderRecord;
renderRecord=function(){beforeAuditRecord();if(recordScreen==='entry'&&authState==='member'&&!profileComplete())q('.record-start').insertAdjacentHTML('afterend',auditContinue());
 if(recordScreen==='history'){page.querySelectorAll('.record-history-row').forEach(row=>{row.insertAdjacentHTML('beforeend','<button class="record-edit" data-audit="record-edit" data-id="'+row.dataset.id+'">Sửa</button>');row.querySelector('.record-delete').innerHTML='<span class="original-trash" aria-hidden="true"></span>';});}
 if(recordScreen==='seven')renderSevenAudit();
 if(recordScreen==='form'&&auditOffline)q('.record-main').insertAdjacentHTML('beforeend','<p class="audit-save-error" role="alert">Đang mô phỏng mất kết nối. Bản nháp sẽ được giữ khi lưu thất bại.</p>');
};
function renderSevenAudit(){const result=AuditModel.a8(digestiveRecords,recordToday,recordFirstUse);let h='<h3>'+result.start+' – '+result.end+'</h3><h3>Kết luận từ Nhật ký tiêu hóa</h3><section><h4>Tổng quan</h4><p>'+result.current.rows.length+' bản ghi trên '+result.current.days+' ngày có dữ liệu.</p><p>'+(!result.statistics?'Chưa đủ 7 ngày sử dụng và 3 bản ghi để tổng hợp theo ngưỡng.':'Đủ ngưỡng thống kê. Điều này chưa đủ để nhận xét xu hướng.')+'</p></section>';
 for(const key of ['shape','color','duration','feeling','amount','adhesion']){const f=result.fields[key],label=key==='duration'?'Thời lượng':recordFields[key][0];const counts=AuditModel.groupCounts(f.current,key);h+='<section class="a8-section"><h4>'+label+'</h4><p>'+f.current.length+' có dữ liệu · '+f.missing+' chưa ghi nhận</p><p>'+(Object.entries(counts).map(([v,n])=>escapeRecord(v)+(key==='duration'?' phút':'')+': '+n+'/'+f.current.length).join(' · ')||'Chưa có dữ liệu')+'</p>'+(key==='duration'&&f.current.length?'<p>Trung bình: '+(f.current.reduce((s,r)=>s+Number(r.duration),0)/f.current.length).toFixed(1)+' phút.</p>':'')+'<p>'+(!f.compare?'Chưa đủ căn cứ để so sánh giữa hai tuần.':'Đủ dữ liệu so sánh đặc điểm này. Chỉ mô tả dữ kiện đã ghi nhận.')+'</p>'+(f.compare?'<p>Tuần trước: '+Object.entries(AuditModel.groupCounts(f.previous,key)).map(([v,n])=>escapeRecord(v)+': '+n+'/'+f.previous.length).join(' · ')+'</p>':'')+'</section>';}
 h+='<section><h4>Giới hạn dữ liệu</h4><p>Mỗi tuần cần ≥7 bản ghi, trên ≥3 ngày; khoảng cách giữa các ngày có dữ liệu ≤4 ngày. Mỗi đặc điểm cần ≥5 giá trị ở cả hai tuần.</p><p>'+(result.current.gap||result.previous.gap?'Các bản ghi phân bố không đều: có khoảng cách vượt quá 4 ngày. ':'')+'Ngày không có bản ghi là thiếu thông tin. Không dùng Nhật ký bữa ăn.</p></section><section><h4>Lưu ý khi cần</h4><p>[Nội dung diễn giải được kiểm chứng — chưa tích hợp]</p></section><section><h4>Gợi ý từ SmartMeal</h4><p>[Chờ nội dung được kiểm chứng; không suy luận nguyên nhân từ món đã ăn]</p></section><p class="record-note">[Biểu đồ thống kê chưa thiết kế trong vòng này]</p>';q('.record-main').innerHTML=h;
}
const beforeAuditPersona=renderPersona;
renderPersona=function(){beforeAuditPersona();const info=q('.persona-information');info.insertAdjacentHTML('afterend','<section class="persona-information persona-description" aria-label="Khung mô tả nhân vật chưa thiết lập"><div class="persona-description-row"><b>Thiết lập nhân vật</b><span>Chưa thiết lập</span></div><div class="persona-empty-lines" aria-label="Vị trí nội dung chưa được duyệt"><i></i><i></i><i></i></div><div class="persona-description-row"><b>Phong cách đối thoại</b><span>Chưa thiết lập</span></div><div class="persona-empty-lines" aria-label="Vị trí nội dung chưa được duyệt"><i></i><i></i></div></section>');};
const beforeAuditSavePersona=savePersona;savePersona=function(){beforeAuditSavePersona();const identity=q('.sm-identity');identity.replaceChildren(document.createTextNode(personaSlots[personaSaved].name),document.createElement('br'));const sub=document.createElement('span');sub.textContent=personaSlots[personaSaved].intro;identity.append(sub);};
function addNotebookActions(){messages.querySelectorAll('.recommendation').forEach(card=>{if(card.querySelector('[data-audit="save-recipe"]'))return;card.insertAdjacentHTML('beforeend','<button data-audit="save-recipe" data-id="'+card.dataset.recommendation+'">Lưu vào Sổ tay</button><span class="recipe-save-status" role="status"></span>');});}
const beforeAuditGenerate=generateRecommendations;generateRecommendations=function(){beforeAuditGenerate();addNotebookActions();};
const beforeAuditSend=sendAI;sendAI=function(text){if(q('#sm-scenario').value!=='chat'&&!requireProfile('ai'))return;beforeAuditSend(text);};
// The preview recognizes only these explicit sample edits, not arbitrary language.
sendAI=function(text){if(!text.trim())return;const scenario=q('#sm-scenario').value;if(scenario!=='chat'&&!requireProfile('ai'))return;if(scenario==='clear'&&aiGenerated){const lower=text.toLocaleLowerCase('vi');const taste=['Thanh đạm','Đậm đà','Trung tính'].find(v=>lower.includes(v.toLocaleLowerCase('vi')));if(taste)committedConditions.taste=taste;const minutes=lower.match(/(\d+)\s*phút/);if(minutes&&Number(minutes[1])>0)committedConditions.time=Number(minutes[1]);}beforeAuditSend(text);};
new MutationObserver(()=>{const shell=q('.record-shell');if(!shell)return;const blocked=!!shell.querySelector('.record-modal-backdrop');shell.querySelectorAll(':scope > header,:scope > main,:scope > footer,:scope > nav').forEach(n=>n.inert=blocked);}).observe(page,{childList:true,subtree:true});
let recipeUpdatePending=null;
function recipeUpdateDialog(id,appearance=false){const old=recipeCatalog.find(r=>r.id===id);recipeUpdatePending={...old,description:'[Công thức mới — mẫu]',imageId:appearance?'anh-'+id+'-v2':old.imageId,appearance};auditDialog('Cập nhật công thức?','Thay phiên bản đã lưu bằng công thức mới?',[['recipe-update-yes','Có'],['recipe-update-no','Không']]);}
root.addEventListener('submit',e=>{if(e.target.id!=='audit-auth-form')return;e.preventDefault();if(!e.target.reportValidity())return;if(auditOffline){q('.account-error').textContent='Chưa kết nối. Hãy thử lại.';return;}if(accountMode==='register'){accountMode='verify';renderAccount();}else if(accountMode==='reset'){accountMode='reset-sent';renderAccount();}else{authState='member';renderWelcome();if(profileComplete())enterDemoDay();else accountBack();}});
root.addEventListener('input',e=>{if(e.target.dataset.profile)profileDraft[e.target.dataset.profile]=e.target.value;});
root.addEventListener('change',e=>{if(e.target.dataset.profile)profileDraft[e.target.dataset.profile]=e.target.value;});
root.addEventListener('click',e=>{
 const edit=e.target.closest('[data-home="account"]');if(edit){e.stopImmediatePropagation();homeScroll=q('.hp-scroll').scrollTop;openProfile();return;}
 const rec=e.target.closest('[data-record]');if(rec){if(['start','add'].includes(rec.dataset.record)&&!requireProfile('record')){e.stopImmediatePropagation();return;}if(rec.dataset.record==='back'&&recordScreen==='form'){recordDraft={};recordError='';}if(rec.dataset.record==='save'&&auditOffline){e.stopImmediatePropagation();q('.audit-save-error')?.remove();q('.record-main').insertAdjacentHTML('beforeend','<p class="audit-save-error" role="alert">Không thể lưu. Bản nháp vẫn giữ nguyên; hãy kết nối rồi thử lại.</p>');return;}}
 const b=e.target.closest('[data-audit]');if(!b)return;e.stopImmediatePropagation();const a=b.dataset.audit;
 if(a==='bowel'){homeScroll=q('.hp-scroll').scrollTop;recordOpen('entry');}
 if(a==='auth-entry')openAccount();
 if(a.startsWith('auth-')&&a!=='auth-entry'){accountMode=a.slice(5);renderAccount();}
 if(a==='account-back'){if(q('[data-profile]')&&JSON.stringify(profileDraft)!==JSON.stringify(profileData))auditDialog('Lưu thay đổi?','',[['profile-save-leave','Lưu thay đổi'],['profile-discard','Không lưu'],['dialog-close','Tiếp tục chỉnh sửa']]);else accountBack();}
 if(a==='profile'){const origin=q('.saved-shell')?'saved':q('.record-shell')?'record':'home';openProfile(origin);}
 if(a==='save-profile'||a==='profile-save-leave'){closeAuditDialog();if(saveProfile()){enterDemoDay();}}
 if(a==='profile-discard'){profileDraft={...profileData};closeAuditDialog();accountBack();}
 if(a==='dialog-close')closeAuditDialog();
 if(a==='verified'){authState='member';renderWelcome();openProfile(accountOrigin);}
 if(a==='logout'){authState='guest';digestivePermission.reset();syncPermission();renderWelcome();accountBack();}
 if(a==='delete-account'){accountMode='delete-account';renderAccount();}
 if(a==='record-edit'){recordHistoryScroll=q('.record-history').scrollTop;recordFormOrigin='history';recordDraft={...digestiveRecords.find(r=>r.id===b.dataset.id)};recordError='';recordOpen('form');}
 if(a==='save-recipe'){const r=recipeCatalog.find(r=>r.id===b.dataset.id);const result=AuditModel.saveRecipe(savedRecipes,r);savedRecipes=result.rows;b.parentElement.querySelector('.recipe-save-status').textContent=result.status;}
 if(a==='recipe-update')recipeUpdateDialog(b.dataset.id,b.dataset.appearance==='true');
 if(a==='recipe-update-yes'){savedRecipes=AuditModel.updateRecipe(savedRecipes,recipeUpdatePending,true,recipeUpdatePending.appearance);const index=recipeCatalog.findIndex(r=>r.id===recipeUpdatePending.id);recipeCatalog[index]={...savedRecipes.find(r=>r.id===recipeUpdatePending.id)};closeAuditDialog();savedOpen();}
 if(a==='recipe-update-no'){closeAuditDialog();savedOpen();}
 if(a==='goal-keep'||a==='goal-skip'){goalAsked=recordToday;closeAuditDialog();show('home');}
 if(a==='goal-change'){closeAuditDialog();openProfile();}
},true);
root.addEventListener('keydown',e=>{const modal=q('.audit-overlay');if(!modal)return;if(e.key==='Tab'){const bs=[...modal.querySelectorAll('button')],i=bs.indexOf(document.activeElement);e.preventDefault();bs[(i+(e.shiftKey?-1:1)+bs.length)%bs.length].focus();}});
const auditStates={'audit-home':'Hồ sơ · Chưa đăng nhập','audit-member':'Hồ sơ · Đã hoàn tất (mẫu)','audit-incomplete':'Hồ sơ · Chưa hoàn tất','audit-persona':'Hồ sơ AI · Khung mô tả trống','audit-edit-record':'Ghi lại · Sửa bản ghi','audit-offline':'Ghi lại · Lỗi lưu giữ nháp','audit-a8':'A8 · Hai tuần đủ dữ liệu','audit-a8-missing':'A8 · Thiếu một đặc điểm','audit-goal':'Hồ sơ · Hỏi mục tiêu sau 7 ngày','audit-streak':'Hồ sơ · Mở ứng dụng trong ngày','audit-saved-update':'Sổ tay · Cập nhật công thức','audit-no-combo':'AI · Có món đơn, chưa có combo','audit-ambiguous':'AI · Nguyên liệu chưa rõ'};
Object.entries(auditStates).forEach(([v,n])=>q('#sm-state').append(new Option(n,v)));
function auditReview(state){auditOffline=false;overlay.hidden=true;page.inert=false;authState=state==='audit-home'?'guest':'member';if(state==='audit-incomplete')profileData={...profileData,goal:'',taste:''};else if(authState==='member')profileData={...profileData,goal:'[Mục tiêu mẫu]',taste:'Trung tính'};renderWelcome();
 if(['audit-home','audit-member','audit-incomplete'].includes(state))show('home');
 if(state==='audit-persona')personaOpen();
 if(state==='audit-edit-record'){recordOpen('history');q('[data-audit="record-edit"]').click();}
 if(state==='audit-offline'){auditOffline=true;recordNew('entry');recordDraft={...recordFixtures()[0]};renderRecord();}
 if(state==='audit-a8'||state==='audit-a8-missing'){recordFirstUse='2026-09-01';digestiveRecords=Array.from({length:14},(_,i)=>({...recordFixtures()[0],id:'a8-'+i,date:AuditModel.iso(AuditModel.day(recordToday)-i),duration:4+i,shape:state==='audit-a8-missing'&&i%2===0?undefined:recordFields.shape[1][i%7]}));recordOpen('seven');}
 if(state==='audit-streak')enterDemoDay();
 if(state==='audit-goal'){show('home');auditDialog('Mục tiêu dinh dưỡng','Bạn có muốn thay đổi mục tiêu cho 7 ngày tiếp theo?',[['goal-keep','Giữ nguyên'],['goal-change','Thay đổi'],['goal-skip','Bỏ qua']]);}
 if(state==='audit-saved-update'){savedOpen();q('.saved-list').insertAdjacentHTML('afterbegin','<div><button data-audit="recipe-update" data-id="s1">Cập nhật công thức · mẫu</button></div>');}
 if(state==='audit-no-combo'){generateRecommendations();messages.querySelectorAll('.recommendation').forEach(c=>{if(c.dataset.recommendation.startsWith('c'))c.remove();});addAIText('Chưa tạo được combo phù hợp · trạng thái mẫu. Các món đơn hợp lệ vẫn được hiển thị.');}
 if(state==='audit-ambiguous'){page.hidden=true;started=true;messages.hidden=false;appendChat('Tôi có cải và cá · mẫu');addAIText('Hãy nhập tên cụ thể của cải và cá để tiếp tục tạo món.');}
 q('#sm-state').value=state;
}
