// Placeholder recipe records are demo data, not validated SmartMeal recipes.
const savedFixture=()=>[
 {id:'s1',type:'single',name:'Món gà · mẫu',ingredient:'Thịt',main:'Gà',description:'[Mô tả ngắn]',goal:'',nutrient:'',imageId:'anh-s1'},
 {id:'s2',type:'single',name:'Món trứng · mẫu',ingredient:'Trứng',main:'Trứng',description:'[Mô tả ngắn]',goal:'',nutrient:'',imageId:'anh-s2'},
 {id:'s3',type:'single',name:'Món cá · mẫu',ingredient:'Cá',main:'Cá',description:'[Mô tả ngắn]',goal:'',nutrient:'',imageId:'anh-s3'},
 {id:'s4',type:'single',name:'Món rau · mẫu',ingredient:'Rau',main:'Rau',description:'[Mô tả ngắn]',goal:'',nutrient:'',imageId:'anh-s4'},
 {id:'s5',type:'single',name:'Món cơm · mẫu',ingredient:'Tinh bột',main:'Gạo',description:'[Mô tả ngắn]',goal:'',nutrient:'',imageId:'anh-s5'},
 {id:'s6',type:'single',name:'Món táo · mẫu',ingredient:'Hoa quả',main:'Táo',description:'[Mô tả ngắn]',goal:'',nutrient:'',imageId:'anh-s6'},
 {id:'c1',type:'combo',name:'Combo A · mẫu',main:'Gà, rau, gạo',description:'[Tóm tắt bữa ăn]',goal:'',nutrient:'',imageId:'anh-c1',parts:['s1','s4','s5']},
 {id:'c2',type:'combo',name:'Combo B · mẫu',main:'Cá, rau, gạo',description:'[Tóm tắt bữa ăn]',goal:'',nutrient:'',imageId:'anh-c2',parts:['s3','s4','s5']}
];
const recipeCatalog=savedFixture();let savedRecipes=[...recipeCatalog],savedMode='single',savedQuery='',savedIngredient='',savedListScroll=0,recipeRoute=[];
const normalizeSaved=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d').toLowerCase();
function savedNav(){const temp=document.createElement('div');temp.innerHTML=document.getElementById('sm-home-template').innerHTML;const nav=temp.querySelector('.hp-nav');nav.querySelectorAll('[aria-current]').forEach(n=>n.removeAttribute('aria-current'));nav.querySelector('[data-name="Sổ tay"]').setAttribute('aria-current','page');return nav.outerHTML;}
function savedOpen(){page.hidden=false;overlay.hidden=true;q('#sm-state').value='saved';renderSaved();q('#sm-caption').textContent='Sổ tay · NHÁP / CHƯA PHÊ DUYỆT. Dữ liệu mẫu, ảnh có thể thay thế. Xóa trực tiếp chỉ khỏi Sổ tay; Nhật ký giữ nguyên.';}
function savedRows(){return savedRecipes.filter(r=>r.type===savedMode&&(savedMode==='combo'||!savedIngredient||r.ingredient===savedIngredient)&&normalizeSaved([r.name,r.main,r.goal,r.nutrient].join(' ')).includes(normalizeSaved(savedQuery)));}
function savedCards(){const rows=savedRows();return rows.length?rows.map(r=>'<div class="saved-card-wrap" data-saved-id="'+r.id+'"><button class="saved-delete" data-saved="delete" data-id="'+r.id+'" aria-label="Xóa '+r.name+'"><span class="original-trash" aria-hidden="true"></span></button><button class="saved-card" data-saved="detail" data-id="'+r.id+'"><span class="saved-plate" data-image-id="'+r.imageId+'">[Ảnh '+(r.type==='combo'?'cả bữa':'món')+']</span><span class="saved-copy"><strong>'+r.name+'</strong><p>'+r.description+'</p>'+(r.type==='single'?'<span class="saved-tag">[Nhãn có bằng chứng]</span>':'')+'</span></button></div>').join(''):'<p class="saved-empty">'+(savedQuery||savedIngredient?'Không có kết quả phù hợp':'Chưa lưu '+(savedMode==='single'?'món ăn':'combo'))+'</p>';}
function renderSaved(){
 page.innerHTML='<div class="saved-shell"><div class="record-badge">NHÁP / CHƯA PHÊ DUYỆT · DỮ LIỆU MẪU</div><header class="saved-top"><h2 class="saved-title">Sổ tay</h2><input id="saved-search" aria-label="Tìm món đã lưu theo tên, nguyên liệu, mục tiêu hoặc nhóm chất đã xác minh" placeholder="Tìm trong món và combo đã lưu" value="'+escapeRecord(savedQuery)+'"></header><div class="saved-tabs"><button data-saved="mode" data-value="single" aria-pressed="'+(savedMode==='single')+'">Món đơn</button><button data-saved="mode" data-value="combo" aria-pressed="'+(savedMode==='combo')+'">Combo</button></div>'+(savedMode==='single'?'<div class="saved-filters" aria-label="Lọc nguyên liệu">'+['Thịt','Trứng','Cá','Rau','Tinh bột','Hoa quả'].map(n=>'<button data-saved="ingredient" data-value="'+n+'" aria-pressed="'+(savedIngredient===n)+'">'+n+'</button>').join('')+'</div>':'')+'<main class="saved-list '+(savedMode==='combo'?'saved-combos':'')+'">'+(savedMode==='single'?'<div class="saved-grid">':'')+savedCards()+(savedMode==='single'?'</div>':'')+'</main>'+savedNav()+'</div>';enhanceIcons();q('.saved-list').scrollTop=savedListScroll;savedWireSwipes();
}
function savedWireSwipes(){page.querySelectorAll('.saved-card-wrap').forEach(row=>{let start=null,moved=false;row.onpointerdown=e=>{start=e.clientX;moved=false;};row.onpointerup=e=>{if(start!==null&&Math.abs(start-e.clientX)>35){row.classList.toggle('swiped',start>e.clientX);moved=true;}start=null;};row.addEventListener('click',e=>{if(moved){e.stopPropagation();moved=false;}},true);row.onkeydown=e=>{if(e.key==='ArrowLeft'){row.classList.add('swiped');row.querySelector('.saved-delete').focus();}};});}
// One shared detail shell: this project only supplied an existing placeholder, not the final approved component.
function openSharedRecipe(id,origin='saved'){const r=recipeCatalog.find(r=>r.id===id);if(!r)return;recipeRoute.push({id,origin});renderRecipe(r);}
function renderRecipe(r){page.hidden=false;let h='<div class="recipe-shell">'+recordHeader(r.type==='single'?'Chi tiết món':'Chi tiết combo').replace('data-record="back"','data-saved="back-detail"')+'<main class="recipe-content"><section class="recipe-poster"><span>[Thông tin định tính đã xác minh]</span><div class="recipe-hero" data-image-id="'+r.imageId+'">[Cùng ảnh '+r.imageId+']</div><strong>'+r.name+'</strong></section>';
 if(r.type==='single')h+='<h3>Nguyên liệu chính</h3><p>['+r.main+' — dữ liệu mẫu; định lượng chờ xác minh]</p><h3>Gia vị</h3><p>[Gia vị của công thức đã xác minh]</p><h3>Cách làm</h3><ol><li>[Bước nấu đã xác minh]</li><li>[Bước tiếp theo]</li></ol><h3>Thay thế gia vị</h3><p>[Chỉ phương án đã xác minh; không tự thay nguyên liệu chính]</p>';
 else h+='<h3>Tóm tắt</h3><p>[Thông tin định tính có bằng chứng]</p><p>Loại bữa: [Dữ liệu của combo]</p><p>Tổng thời gian chuẩn bị: [Chưa cung cấp]</p><h3>Các món trong combo</h3>'+r.parts.map(id=>{const d=recipeCatalog.find(x=>x.id===id);return '<button class="recipe-part" data-saved="component" data-id="'+id+'"><span class="recipe-thumb" data-image-id="'+d.imageId+'">[Ảnh]</span><span>'+d.name+'</span><span>›</span></button>';}).join('');
 page.innerHTML=h+'</main></div>';q('#sm-caption').textContent='Chi tiết dùng chung · Khung chờ component đã duyệt. Không có component hoàn chỉnh trong bản cục bộ; Figma chưa truy cập được. Ảnh giữ cùng mã với thẻ món/combo.';
}
root.addEventListener('input',e=>{if(e.target.id==='saved-search'){savedQuery=e.target.value;savedListScroll=0;q('.saved-list').innerHTML=savedCards();savedWireSwipes();}});
root.addEventListener('click',e=>{const b=e.target.closest('[data-saved]');if(!b)return;const a=b.dataset.saved;
 if(a==='mode'){savedMode=b.dataset.value;savedListScroll=0;renderSaved();}
 if(a==='ingredient'){savedIngredient=savedIngredient===b.dataset.value?'':b.dataset.value;savedListScroll=0;renderSaved();}
 if(a==='delete'){savedListScroll=q('.saved-list').scrollTop;savedRecipes=savedRecipes.filter(r=>r.id!==b.dataset.id);renderSaved();}
 if(a==='detail'){savedListScroll=q('.saved-list').scrollTop;openSharedRecipe(b.dataset.id);}
 if(a==='component')openSharedRecipe(b.dataset.id,'combo');
 if(a==='back-detail'){const last=recipeRoute.pop();if(recipeRoute.length)renderRecipe(recipeCatalog.find(r=>r.id===recipeRoute.at(-1).id));else if(last.origin==='ai'){page.hidden=true;history.scrollTop=scroll;}else savedOpen();}
});
// Generic carousel slots exercise the approved behavior without approving a character roster or a default identity.
const personaSlots=[{name:'[Nhân vật A]',intro:'[Giới thiệu A — chờ duyệt]',color:'#FFF0B0'},{name:'[Nhân vật B]',intro:'[Giới thiệu B — chờ duyệt]',color:'#CFE6AF'},{name:'[Nhân vật C]',intro:'[Giới thiệu C — chờ duyệt]',color:'#FFFCF0'}];
let personaPreview=0,personaSaved=0,personaChatScroll=0,personaMessage='',personaPreviousScreen='welcome';
function personaOpen(){personaChatScroll=history.scrollTop;personaPreviousScreen=started?'active':'welcome';personaPreview=personaSaved;personaMessage='';page.hidden=false;overlay.hidden=true;renderPersona();q('#sm-state').value='persona';q('#sm-caption').textContent='Hồ sơ AI · Khung mẫu A/B/C, chưa phải danh sách nhân vật. Dấu tích và màu nền chỉ mô phỏng. Nhân vật mặc định, ảnh, tên, giới thiệu và màu riêng chưa được duyệt.';}
function renderPersona(){page.innerHTML='<div class="persona-shell" style="--persona-bg:'+personaSlots[personaPreview].color+'"><div class="record-badge">NHÁP · NHÂN VẬT VÀ MÀU RIÊNG CHƯA DUYỆT</div><header class="record-head"><button data-persona="back" aria-label="Quay lại hội thoại">'+emoji('back')+'</button><h2>Hồ sơ AI</h2><button data-persona="save">Lưu</button></header><main class="persona-content"><div class="persona-window" role="group" aria-label="Vuốt ngang để xem nhân vật" tabindex="0"><div class="persona-track">'+personaSlots.map((p,i)=>'<div class="persona-card" data-slot="'+i+'">[Chân dung '+String.fromCharCode(65+i)+'<br>Chờ duyệt riêng]'+(i===personaSaved?'<span class="persona-check" aria-label="Đang sử dụng — trạng thái mẫu">✓</span>':'')+'</div>').join('')+'</div></div><div class="persona-dots" aria-label="Vị trí nhân vật">'+personaSlots.map(()=>'<span></span>').join('')+'</div><p class="persona-message" role="status">'+personaMessage+'</p><section class="persona-information"><p><b>Tên</b><span class="persona-name"></span></p><p><b>Giới thiệu</b><span class="persona-intro"></span></p></section><section class="persona-information"><p><b>Độ dài trả lời</b><span>[Các lựa chọn chờ duyệt]</span></p><p><b>Giọng đọc</b><span>[Danh sách chờ duyệt]</span></p><p><b>Tốc độ đọc</b><span>[Giá trị chờ duyệt]</span></p></section></main></div>';syncPersona();const win=q('.persona-window');let start=null;win.onpointerdown=e=>{start=e.clientX;win.setPointerCapture(e.pointerId);};win.onpointerup=e=>{if(start!==null&&Math.abs(e.clientX-start)>35)previewPersona(personaPreview+(e.clientX<start?1:-1));start=null;};win.onpointercancel=()=>start=null;win.onkeydown=e=>{if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();previewPersona(personaPreview+(e.key==='ArrowRight'?1:-1));}};}
function syncPersona(){q('.persona-track').style.transform='translateX('+(-135-personaPreview*292)+'px)';q('.persona-shell').style.setProperty('--persona-bg',personaSlots[personaPreview].color);page.querySelectorAll('.persona-card').forEach((c,i)=>{c.classList.toggle('centered',i===personaPreview);c.classList.toggle('before',i<personaPreview);});page.querySelectorAll('.persona-dots span').forEach((d,i)=>d.classList.toggle('active',i===personaPreview));q('.persona-name').textContent=personaSlots[personaPreview].name;q('.persona-intro').textContent=personaSlots[personaPreview].intro;}
function previewPersona(i){personaPreview=Math.max(0,Math.min(personaSlots.length-1,i));personaMessage='';q('.persona-message').textContent=personaPreview===personaSaved?'Đang sử dụng · mẫu':'Đang xem thử · chưa lưu';syncPersona();}
function savePersona(){personaSaved=personaPreview;personaMessage='Đã lưu lựa chọn · mô phỏng';renderPersona();q('.sm-identity strong')&&(q('.sm-identity strong').textContent=personaSlots[personaSaved].name);root.querySelectorAll('.sm-ai>header .sm-avatar,.sm-airow>.sm-avatar').forEach(a=>{a.textContent='[Ảnh '+String.fromCharCode(65+personaSaved)+']';});}
function leavePersona(){show(personaPreviousScreen);history.scrollTop=personaChatScroll;}
function personaLeaveDialog(){q('.persona-shell').insertAdjacentHTML('beforeend','<div class="persona-modal" role="dialog" aria-modal="true" aria-label="Lưu thay đổi?"><div><h3>Lưu thay đổi?</h3><button data-persona="save-leave">Lưu thay đổi</button><button data-persona="discard">Không lưu</button><button data-persona="continue">Tiếp tục chỉnh sửa</button></div></div>');q('.persona-content').inert=true;q('.persona-shell header').inert=true;q('[data-persona="save-leave"]').focus();}
root.addEventListener('click',e=>{const b=e.target.closest('[data-persona]');if(!b)return;const a=b.dataset.persona;if(a==='save')savePersona();if(a==='back'){if(personaPreview!==personaSaved)personaLeaveDialog();else leavePersona();}if(a==='save-leave'){savePersona();leavePersona();}if(a==='discard'){personaPreview=personaSaved;leavePersona();}if(a==='continue'){q('.persona-modal').remove();q('.persona-content').inert=false;q('.persona-shell header').inert=false;q('[data-persona="back"]').focus();}});
root.addEventListener('keydown',e=>{const modal=q('.persona-modal');if(!modal)return;if(e.key==='Tab'){e.preventDefault();const bs=[...modal.querySelectorAll('button')],i=bs.indexOf(document.activeElement);bs[(i+(e.shiftKey?-1:1)+bs.length)%bs.length].focus();}if(e.key==='Escape')q('[data-persona="continue"]').click();});
root.addEventListener('click',e=>{const b=e.target.closest('[data-name="Sổ tay"],[data-act="settings"],[data-act="detail"]');if(!b)return;e.stopImmediatePropagation();if(b.dataset.name==='Sổ tay')savedOpen();else if(b.dataset.act==='settings')personaOpen();else{scroll=history.scrollTop;openSharedRecipe('s1','ai');}},true);
window.addEventListener('message',e=>{if(e.source===q('.diary-frame')?.contentWindow&&e.data?.type==='smartmeal-nav'&&e.data.name==='Sổ tay')savedOpen();});
const savedStates={saved:'Sổ tay · Món đơn','saved-combo':'Sổ tay · Combo','saved-search':'Sổ tay · Tìm kiếm','saved-filter':'Sổ tay · Lọc nguyên liệu','saved-empty':'Sổ tay · Trống','saved-none':'Sổ tay · Không có kết quả','saved-swipe':'Sổ tay · Vuốt món đơn','saved-combo-swipe':'Sổ tay · Vuốt combo','saved-detail':'Chi tiết món dùng chung','saved-combo-detail':'Chi tiết combo dùng chung',persona:'Hồ sơ AI · Ban đầu','persona-preview':'Hồ sơ AI · Xem thử chưa lưu','persona-success':'Hồ sơ AI · Đã lưu','persona-unsaved':'Hồ sơ AI · Rời khi chưa lưu','diary-before':'Nhật ký · Modal trước sửa','diary-after':'Nhật ký · Modal sau sửa','diary-bottom':'Nhật ký · Modal cuối danh sách dài','diary-short':'Nhật ký · Modal danh sách ngắn'};
Object.entries(savedStates).forEach(([v,n])=>q('#sm-state').append(new Option(n,v)));
function reviewExtension(state){q('#sm-state').value=state;if(state.startsWith('diary-')){renderDiaryModalReview(state==='diary-before',state);return;}if(state.startsWith('persona')){personaOpen();if(state!=='persona'){previewPersona((personaSaved+1)%3);if(state==='persona-success')savePersona();if(state==='persona-unsaved')personaLeaveDialog();}q('#sm-state').value=state;return;}savedRecipes=savedFixture();savedMode=state.includes('combo')?'combo':'single';savedQuery=state==='saved-search'?'gà':state==='saved-none'?'Không có món này':'';savedIngredient=state==='saved-filter'?'Rau':'';savedListScroll=0;if(state==='saved-empty')savedRecipes=[];savedOpen();q('#sm-state').value=state;if(state.endsWith('swipe'))q('.saved-card-wrap').classList.add('swiped');if(state==='saved-detail'||state==='saved-combo-detail')openSharedRecipe(state==='saved-detail'?'s1':'c1');}
function renderDiaryModalReview(before,stateName){page.hidden=false;overlay.hidden=true;const iframe=document.createElement('iframe');iframe.className='diary-frame';iframe.title=before?'Nhật ký trước sửa':'Nhật ký sau sửa';let source=diarySource.replace('RICE_ASSET_TOKEN',riceAsset);if(before)source=source.replace('z-index:100;isolation:isolate;','z-index:auto;');const reviewSetup=stateName==='diary-bottom'?'customRows=Array.from({length:12},(_,i)=>({...SmartMealDiary.records("current")[0],id:"long-"+i}));':stateName==='diary-short'?'customRows=SmartMealDiary.records("current").slice(0,1);':'';source=source.replace('</body>','<script>'+reviewSetup+'state="swipe";render();const ds=document.querySelector(".scroll");if('+JSON.stringify(stateName==='diary-bottom')+')ds.scrollTop=ds.scrollHeight;const bs=document.querySelectorAll("[data-action=delete]");bs['+(stateName==='diary-bottom'?'bs.length-1':'0')+'].click();<\/script></body>');iframe.srcdoc=source;page.replaceChildren(iframe);q('#sm-caption').textContent=before?'Trước sửa (tái hiện từ bản cũ): thẻ món z-index 1 nằm trên modal không có z-index.':'Sau sửa: modal z-index 100 ở cấp màn hình, chặn danh sách và điều hướng, giữ cuộn khi đóng. Mục xóa vẫn là một đợt ăn.';}
